;VAULT-TEC (82858-832) demo
exten => 82858832,1,Answer
same => n,PlayTones(400+415/1000,0/2000)
same => n,Wait(1)
same => n,Background(sorry&digits/1&digits/hundred&vm-and&digits/1&digits/million&queue-quantity2&queue-holdtime&digits/70&digits/8&digits/thousand&digits/6&digits/hundred&digits/40&digits/3&hours&privacy-thankyou)
same => n,Playback(reno_project-system)
same => n,Wait(1)
same => n,GoTo(4)
