;Connection test
;Say connected PBX ID & extension
exten => 111,1,Answer
same => n,PlayTones(400+415/1000,0/2000)
same => n,Wait(1)
same => n,SayAlpha(pbx)
same => n,Playback(is)
same => n,SayAlpha(${GLOBAL(PBXID)})
same => n,Wait(1)
same => n,Playback(your&number&is)
same => n,SayDigits(${CALLERID(num)})
same => n,Playback(demo-congrats&demo-thanks)
same => n,Wait(1)
same => n,PlayTones(400/500,0/500)
same => n,Wait(5)
