[general]
bindport = 4569
bindaddr = ::
bindaddr = 0.0.0.0
allow=opus
allow=speex
allow=g722
mailboxdetail=yes

[IAX-TRUNK-osaka-pbx.voip.co.nz]
type = user
username = IAX-TRUNK-osaka-pbx.voip.yuriko.co.nz
secret =
context=default
auth = rsa
encryption = yes

[INTER-AZ]
type = peer
description = to AZ-B
username = IAX-TRUNK-osaka-pbx.voip.yuriko.co.nz
secret =
auth = rsa
forceencryption = yes
host = b.osaka-pbx.voip.yuriko.co.nz
qualify = yes
trunk = yes
