;Listener can change music by push dial button.
[general]

[default]
mode=playlist
entry=/var/lib/asterisk/moh/manolo_camp-morning_coffee
digit=1

[macroform-robot_dity]
mode=playlist
entry=/var/lib/asterisk/moh/macroform-robot_dity
digit=2
