[INTER-AZ]
type = registration
transport=transport-udpv6
server_uri = sip:SIP-TRUNK-YURIKO@c.osaka-pbx.voip.yuriko.co.nz
client_uri = sip:SIP-TRUNK-YURIKO@a.osaka-pbx.voip.yuriko.co.nz.
outbound_auth = SIP-TRUNK-YURIKO
