[yuriko@i-0bd16876ddd48b1d3 asterisk]$ cat pjsip.conf
[transport-udpv6]
type=transport
protocol=udp
bind=[::]:5060
allow_reload=yes

[transport-tcpv6]
type=transport
protocol=tcp
bind=[::]:5060
allow_reload=yes
;TCP keepalive settings for 'transport-tcpv6' not set due to PJSIP built without support for setting all options. Consider using bundled PJSIP.
tcp_keepalive_enable=yes

#include "pjsip_trunk_inbound.conf"
#include "pjsip_trunk_outbound_interAZ.conf"
