[SIP-TRUNK-YURIKO]
type = auth
username = SIP-TRUNK-YURIKO
password = 

[SIP-TRUNK-YURIKO]
type = aor
max_contacts = 100
qualify_frequency = 60

[SIP-TRUNK-YURIKO]
type = endpoint
100rel = no
context = default
dtmf_mode = auto
;Codec negotiation order
disallow = all
allow = opus
allow = speex
allow = g722
allow = alaw
allow = ulaw
allow = ilbc
allow = h264
rtp_symmetric = yes
force_rport = yes
rewrite_contact = yes
ice_support = no
direct_media = yes ;Because of IPv6
sdp_session = asterisk
language = ja
aors = SIP-TRUNK-YURIKO
timers = no
rtp_timeout = 30
rtp_timeout_hold = 30
auth = SIP-TRUNK-YURIKO
outbound_auth = SIP-TRUNK-YURIKO
inband_progress = yes
tone_zone = jp
