;Common settings
[phone-defaults](!)
type=wizard
transport=transport-udpv6
accepts_registrations = yes
sends_registrations = no
accepts_auth = yes
sends_auth = no
endpoint/context = default
endpoint/dtmf_mode = rfc4733
endpoint/call_group = 1
endpoint/pickup_group = 1
endpoint/language = en
endpoint/disallow = all
endpoint/allow = opus
endpoint/allow = speex
endpoint/allow = g722
endpoint/allow = ulaw
endpoint/allow = alaw
endpoint/rtp_symmetric = yes
endpoint/force_rport = yes
endpoint/direct_media = no
endpoint/send_pai = yes
endpoint/send_rpid = yes
endpoint/rewrite_contact = yes
endpoint/inband_progress = yes
endpoint/allow_subscribe = yes
endpoint/transport = transport-udpv6
endpoint/callerid = 0000 ;dummy
aor/max_contacts = 2
aor/qualify_frequency = 60
aor/authenticate_qualify = no

#include "pjsip_wizard_snom.conf"
